### ISSUE TITLE
Obtaining the paired LR-HR dataset

### ISSUE THREAD

**Issue by zejinwang** [qc17-THU/DL-SR#1]
Thanks for your excellent work. I am confused about how to obtain the paired WF-SIM dataset without registration. Could you please tell me the specific steps?

**Comment by qc17-THU** [comment]
As described in our manuscript, the WF images were obtained by averaging the raw SIM images (eg. 9 raw SIM images for linear SIM), and the SIM images were reconstructed with the same set of raw SIM images using conventional SIM reconstruction algorithm (eg. fairSIM). In this way, the WF–SIM image pairs are well matched.
