### ISSUE TITLE
script matlab.

### ISSUE THREAD

**Issue by sbelharbi** [qc17-THU/DL-SR#13]
hi,

cc @shakeebmurtaza

- using the current version of the code, i am getting this error when processing 'F-actin_Nonlinear' to generate train/valid set using `DataAugumentation_ForTrain.m`. can you update the code. please test it before publishing. retest over all specimens before publishing so we dont have to come back again for more issues related to generating data. we have already created an [issue](https://github.com/qc17-THU/DL-SR/issues/10#issuecomment-1101255726) about this matter 25 days ago, and so far no answer.
```sh
Generating training data 1/30, SNR 9/9
Generating training data 1/30, SNR 10/9
Index exceeds matrix dimensions.

Error in DataAugumentation_ForTrain (line 189)
        [header, data] = XxReadMRC(files_input{j});
```

- can you fix the case of ER. i am getting this error:
```sh
Error using char
Conversion of element 1 from <missing> to character vector is not supported.

Error in XxSort (line 47)
s1 = char(c2);

Error in DataAugumentation_ForTrain (line 90)
    files_input = XxSort(XxDir(CellList{i}, DataFilter));
```

- can you fix the case of CCPs. error:
```sh
Generating training data 1/30, SNR 8/9
Generating training data 1/30, SNR 9/9
Generating training data 1/30, SNR 10/9
Index exceeds matrix dimensions.

Error in DataAugumentation_ForTrain (line 189)
        [header, data] = XxReadMRC(files_input{j});
```

- can you fix the case of Microtubules . error:
```sh
Generating training data 1/30, SNR 6/9
Generating training data 1/30, SNR 7/9
Generating training data 1/30, SNR 8/9
Generating training data 1/30, SNR 9/9
Generating training data 1/30, SNR 10/9
Index exceeds matrix dimensions.

Error in DataAugumentation_ForTrain (line 189)
        [header, data] = XxReadMRC(files_input{j});
```

- can you provide the exact script that you used to generate all the test set pairs low_resolution-super_resolution under the format `*.tiff` of the four specimens: ccps, er, mts, f-actin, f-actin (non-linear). please test your code before publishing.

please provide the exact same scripts with the exact same configuration that you used so we can produce exactly the same data as you. without these scripts we cant use your data. please avoid asking users to modify or guess anything related to your code. you know better than anyone your data and your matlab code. so, please save everyone headaches, and help us use your public data. the scripts should be ready to use. the user needs only to run them. they have to produce the same data as you since you [said](https://github.com/qc17-THU/DL-SR/issues/9#issuecomment-1101224535) you are unable to upload the ready-to-use data. everyone appreciates your help.

matlab version: same as you (matlab 2017b).

thanks.

**Comment by shakeebmurtaza** [comment]
Hi Sourfiane,
I think the above error in Matlab code could be fixed by my updated script available in the pull request.

**Comment by sbelharbi** [comment]
reminder.

**Comment by qc17-THU** [comment]
I'm struggling with my doctoral dissertation recently and feel sorry for my neglect to issues from you and others until my mentor reminded me just now ...

The error for data of CCPs, MTs and F-actin (nonlinear SIM) you encountered above is induced by the wrong declaration of the variable "train_snr_list" and "validate_snr_list". The uploaded manuscript generates F-actin (linear SIM) training and validation data by default which has 12 different signal levels in BioSR dataset, while the dataset of other specimens only consist of less than 9 signal levels. You may fix the error by simply change the value of these two variables into "1:9". Also, I can upload the data after augmentation if you really need.

BTW, I can indeed feel your anxiety or maybe a little bit anger from your words. I think you are right that I should take the responsibility to help users who appreciate my data and codes. Therefore, sorry again for my late reply and thank you for your suggestions. I'll consolidate the exception handling part for the MATLAB scripts within this week and add a more detailed instruction for users who want to generate their customized datasets from BioSR. 

Best regards.

**Comment by sbelharbi** [comment]
- can update the scripts that generate train, and valid as you said?
- can you upload the scripts that generate test set?
- can you test the scripts before uploading?
- can you confirm that these scripts generate the same exact data as yours? so the comparison to your results will be fair.

thanks.

**Comment by qc17-THU** [comment]
Now I've updated the MATLAB script for data augmentation as I said, added more annotations and exception warning, and ensured that it can be run for all of the five types of specimens in BioSR by only assigning the variable "Specimen" with "CCPs", "ER", "Microtubules", "F-actin" or "F-actin_Nonlinear". You can test it right now.
But I still need some time to made the script for testing data readable and robust enough to upload. If you need, I can give you the exactly testing data I used in my experiments.

**Comment by sbelharbi** [comment]
- i tested the script for the train/valid sets. it works fine.
- can you please provide the script to generate test set? it makes sens to upload one file to generate the dataset instead of uploading the dataset with thousands of files. later, if you want you can upload all subsets. i am waiting for this script.
thanks

**Comment by qc17-THU** [comment]
OK, I'll remind you after I upload it.

**Comment by sbelharbi** [comment]
reminder.
