### ISSUE TITLE
Questions about the training and test data acquisition.

### ISSUE THREAD

**Issue by Luchixiang** [qc17-THU/DL-SR#17]
Hi! Thank you for the awesome data and code. Aftering reading your paper, I still have one question about the training and test data acquisition:

I see that there a SIM_gt.mrc file and a RawSIMData_gt.mrc file in BioSR dataset. What's the difference between these two files? Which one is used for the ground truth in the trianing?

Thanks

**Comment by qc17-THU** [comment]
Hi! The RawSIMData_gt.mrc file includes 9 (3 orientations × 3 phases) diffraction-limited raw SIM images, while the SIM_gt.mrc file includes one SIM SR image used for GT in the training process of DLSR models.

**Comment by Luchixiang** [comment]
So the SIM_gt.mrc is reconstructed using the RawSIMData_gt.mrc through conventional method?

**Comment by qc17-THU** [comment]
Actually, the RawSIMData_gt.mrc is the average of 3 sets of high SNR raw SIM images used for training denoising models, and the SIM_gt.mrc is the average of 3 SIM images reconstructed from these 3 sets of raw SIM images used for DLSR tasks.

**Comment by Luchixiang** [comment]
Do you mean RawSIMData_gt.mrc is the average of the three highest SNR raw SIM images like RawSIMData_level_12.mrc, RawSIMData_level_11.mrc, RawSIMData_level_10.mrc of the F-actin dataset?

**Comment by qc17-THU** [comment]
No, another 3 sets of high SNR data.

**Comment by Luchixiang** [comment]
Got it. Thank you!
