### ISSUE TITLE
Create a virtual environment

### ISSUE THREAD

**Issue by mahirahzaini** [qc17-THU/DL-SR#3]
Hi, I'm just wondering if you can include a virtual environment so I can successfully run the code?

**Comment by qc17-THU** [comment]
Thanks for your suggestion. I have just uploaded a requirements.txt file.

**Comment by mahirahzaini** [comment]
I also wondering if you have data augmentation for testing?

**Comment by qc17-THU** [comment]
Data augmentation for testing is identical to training. I didn't upload the codes but you can just modify the uploaded training codes to a testing version.
