### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by Luchixiang** [qc17-THU/DL-SR#8]
Hi. Thank you for your great work. I notice that just like what you said in the paper. Each set of raw SIM images is averaged to get the WF image while reconstructing to get the SR-SIM. I'm wondering in the BioSR dataset, which one is the reconstructed image(RawSIMData_gt.mrc or SIM_gt.mrc)? And which one did you use as the gtto train the network?
Thank you
Jasper

<img width="212" alt="image" src="https://user-images.githubusercontent.com/35992729/153693921-a611bf7e-ec23-434f-80b5-f9c4680ac666.png">

**Comment by Luchixiang** [comment]
Hi! Sorry to bother you again. I still have one question about data preprocessing.  I find that there are two SIM_GT files in the F-action-nonlinear folder i.e. SIM_gt_a.mrc and SIM_gt_b.mrc. I'm wondering which one did you use to train the network?

**Comment by qc17-THU** [comment]
Hi! SIM_gt.mrc is the final SIM reconstructed SR image, which is used for training, and the RawSIMData_gt.mrc is the raw SIM images of the same ROI. All CNN models in our Nature Methods manuscript were training in an end-to-end manner aiming at directly outputing SR images. 
We use SIM_gt_a.mrc to train the network, while SIM_gt_b.mrc is provided for an overview of all ROIs with a gamma value of 0.6

**Comment by Luchixiang** [comment]
Thanks!
